name: Deploy to Server

on:
  push:
    branches:
      - main  # Déclenchement automatique sur les commits vers la branche 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          echo "Creating SSH key directory in GitHub workspace"
          mkdir -p $GITHUB_WORKSPACE/.ssh  # Créer le répertoire SSH dans le répertoire de travail de GitHub
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > $GITHUB_WORKSPACE/.ssh/github_deploy_key
          chmod 600 $GITHUB_WORKSPACE/.ssh/github_deploy_key
          echo "Adding GitHub to known hosts"
          ssh-keyscan -H 192.168.1.235 >> $GITHUB_WORKSPACE/.ssh/known_hosts
          # Vérifier les fichiers SSH créés
          ls -la $GITHUB_WORKSPACE/.ssh
          cat $GITHUB_WORKSPACE/.ssh/github_deploy_key
          cat $GITHUB_WORKSPACE/.ssh/known_hosts

      - name: Deploy to server
        run: |
          echo "Running deploy script"
          # Tester la connexion SSH avec le serveur avant de procéder
          ssh -i $GITHUB_WORKSPACE/.ssh/github_deploy_key -o StrictHostKeyChecking=no kvothe@192.168.1.235 "echo 'SSH connection successful!'"
          # Si la connexion SSH fonctionne, déployer le code
          ssh -i $GITHUB_WORKSPACE/.ssh/github_deploy_key -o StrictHostKeyChecking=no kvothe@192.168.1.235 "cd /var/www/arnaudlemascon.fr && git pull origin main && sudo chown -R www-data:www-data /var/www/arnaudlemascon.fr"
