name: Deploy to Server

on:
  push:
    branches:
      - main  # Déclenchement automatique sur les commits vers la branche 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      

      - name: Deploy to server
        run: |
          echo "Running deploy script"
          # Tester la connexion SSH avec le serveur avant de procéder
          ssh -i $GITHUB_WORKSPACE/.ssh/github_deploy_key -o StrictHostKeyChecking=no kvothe@192.168.1.235 "echo 'SSH connection successful!'"
          # Si la connexion SSH fonctionne, déployer le code
          ssh -i $GITHUB_WORKSPACE/.ssh/github_deploy_key -o StrictHostKeyChecking=no kvothe@192.168.1.235 "cd /var/www/arnaudlemascon.fr && git pull origin main && sudo chown -R www-data:www-data /var/www/arnaudlemascon.fr"
