name: Deploy to Server

on:
  push:
    branches:
      - main  # Déclenchement automatique sur les commits vers la branche 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/github_deploy_key
          chmod 600 ~/.ssh/github_deploy_key
          ssh-keyscan -H 192.168.1.235 >> ~/.ssh/known_hosts  # Remplace l'IP de ton serveur

      - name: Deploy to server
        run: |
          ssh -i ~/.ssh/github_deploy_key kvothe@192.168.1.235 "cd /var/www/arnaudlemascon.fr && git pull origin main && sudo chown -R www-data:www-data /var/www/arnaudlemascon.fr"
